services:
  db:
    image: mysql:9.1
    env_file: ./.env
    ports:
      - ${DB_PORT}:${DB_LOCAL_PORT}
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      retries: 10
      timeout: 20s

  app:
    build: .
    env_file: ./.env
    depends_on:
      db:
        condition: service_healthy
        restart: true
    links:
      - db
    ports:
      - ${APP_PORT}:${APP_PORT}