services:
  db:
    image: mysql:9.1
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=db-is
      - MYSQL_ROOT_PASSWORD=123456
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      retries: 10
      timeout: 20s

  app:
    image: taisregistry.azurecr.io/tais-app:latest
    build: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
    links:
      - db
    ports:
      - 3000:3000